import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Providers from '@components/Providers';
import AppBar from '@components/AppBar';
import { Box, CssBaseline, Drawer, Toolbar, Typography } from '@mui/material';
import {List, ListItem, ListItemIcon, ListItemText }from '@mui/material';
import SideNav from '@components/SideNav'

const inter = Inter({subsets: ['latin']});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const drawerWidth = 240;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
      <Providers>
          <Box sx={{ display: 'flex' }}>
            {/* <CssBaseline /> */}
            {/* <Drawer
              variant="permanent"
              sx={{
                width: drawerWidth,
                flexShrink: 0,
                [`& .MuiDrawer-paper`]: { width: drawerWidth, boxSizing: 'border-box' },
              }}
            >
              <Toolbar />
              <Box sx={{ overflow: 'auto' }}>
                <Typography variant="h6" noWrap>
                  Invoice App
                </Typography>
              </Box>
              <List>
                <ListItem>
                  <ListItemText primary='hellp'/>
                </ListItem>
                
              </List>
            </Drawer> */}
            <SideNav />
            <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
              <Toolbar />
              {children}
            </Box>
          </Box>
          
        </Providers>
        {/* <Providers>
          {children}
          <AppBar />
          <h1>hellow</h1>
        </Providers> */}
      </body>
    </html>
  );
}
